package net.sagaoftherealms.tools.snes.assembler.opcodes;

public class Opcodes65816 {
    public static final Optcode opt_table[] = {
            new Optcode("ADC #x", 0x69, 4, 0),
            new Optcode("ADC (x)", 0x72, 0xA, 0),
            new Optcode("ADC [x]", 0x67, 0xA, 0),
            new Optcode("ADC (x,X)", 0x61, 0xA, 0),
            new Optcode("ADC (x),Y", 0x71, 0xA, 0),
            new Optcode("ADC (x,S),Y", 0x73, 0xA, 0),
            new Optcode("ADC [x],Y", 0x77, 0xA, 0),
            new Optcode("ADC x", 0x65, 0xA, 2),
            new Optcode("ADC ?", 0x6D, 2, 1),
            new Optcode("ADC &", 0x6F, 3, 0),
            new Optcode("ADC x,X", 0x75, 0xA, 2),
            new Optcode("ADC ?,X", 0x7D, 2, 1),
            new Optcode("ADC &,X", 0x7F, 3, 0),
            new Optcode("ADC ?,Y", 0x79, 2, 0),
            new Optcode("ADC x,S", 0x63, 0xA, 0),
            new Optcode("ADC.B #x", 0x69, 0xA, 0),
            new Optcode("ADC.W #?", 0x69, 2, 0),
            new Optcode("ADC.B (x)", 0x72, 0xA, 0),
            new Optcode("ADC.B [x]", 0x67, 0xA, 0),
            new Optcode("ADC.B (x,X)", 0x61, 0xA, 0),
            new Optcode("ADC.B (x),Y", 0x71, 0xA, 0),
            new Optcode("ADC.B (x,S),Y", 0x73, 0xA, 0),
            new Optcode("ADC.B [x],Y", 0x77, 0xA, 0),
            new Optcode("ADC.B x", 0x65, 0xA, 0),
            new Optcode("ADC.W ?", 0x6D, 2, 0),
            new Optcode("ADC.L &", 0x6F, 3, 0),
            new Optcode("ADC.B x,X", 0x75, 0xA, 0),
            new Optcode("ADC.W ?,X", 0x7D, 2, 0),
            new Optcode("ADC.L &,X", 0x7F, 3, 0),
            new Optcode("ADC.W ?,Y", 0x79, 2, 0),
            new Optcode("ADC.B x,S", 0x63, 0xA, 0),

            new Optcode("AND #x", 0x29, 4, 0),
            new Optcode("AND (x)", 0x32, 0xA, 0),
            new Optcode("AND [x]", 0x27, 0xA, 0),
            new Optcode("AND (x,X)", 0x21, 0xA, 0),
            new Optcode("AND (x),Y", 0x31, 0xA, 0),
            new Optcode("AND (x,S),Y", 0x33, 0xA, 0),
            new Optcode("AND [x],Y", 0x37, 0xA, 0),
            new Optcode("AND x", 0x25, 0xA, 2),
            new Optcode("AND ?", 0x2D, 2, 1),
            new Optcode("AND &", 0x2F, 3, 0),
            new Optcode("AND x,X", 0x35, 0xA, 2),
            new Optcode("AND ?,X", 0x3D, 2, 1),
            new Optcode("AND &,X", 0x3F, 3, 0),
            new Optcode("AND ?,Y", 0x39, 2, 0),
            new Optcode("AND x,S", 0x23, 0xA, 0),
            new Optcode("AND.B #x", 0x29, 0xA, 0),
            new Optcode("AND.W #?", 0x29, 2, 0),
            new Optcode("AND.B (x)", 0x32, 0xA, 0),
            new Optcode("AND.B [x]", 0x27, 0xA, 0),
            new Optcode("AND.B (x,X)", 0x21, 0xA, 0),
            new Optcode("AND.B (x),Y", 0x31, 0xA, 0),
            new Optcode("AND.B (x,S),Y", 0x33, 0xA, 0),
            new Optcode("AND.B [x],Y", 0x37, 0xA, 0),
            new Optcode("AND.B x", 0x25, 0xA, 0),
            new Optcode("AND.W ?", 0x2D, 2, 0),
            new Optcode("AND.L &", 0x2F, 3, 0),
            new Optcode("AND.B x,X", 0x35, 0xA, 0),
            new Optcode("AND.W ?,X", 0x3D, 2, 0),
            new Optcode("AND.L &,X", 0x3F, 3, 0),
            new Optcode("AND.W ?,Y", 0x39, 2, 0),
            new Optcode("AND.B x,S", 0x23, 0xA, 0),

            new Optcode("ASL A", 0x0A, 0, 0),
            new Optcode("ASL", 0x0A, 0, 0),
            new Optcode("ASL x", 0x06, 0xA, 2),
            new Optcode("ASL ?", 0x0E, 2, 0),
            new Optcode("ASL x,X", 0x16, 0xA, 2),
            new Optcode("ASL ?,X", 0x1E, 2, 0),
            new Optcode("ASL.B x", 0x06, 0xA, 0),
            new Optcode("ASL.W ?", 0x0E, 2, 0),
            new Optcode("ASL.B x,X", 0x16, 0xA, 0),
            new Optcode("ASL.W ?,X", 0x1E, 2, 0),

            new Optcode("BCC x", 0x90, 11, 0),
            new Optcode("BCS x", 0xB0, 11, 0),
            new Optcode("BEQ x", 0xF0, 11, 0),
            new Optcode("BNE x", 0xD0, 11, 0),
            new Optcode("BMI x", 0x30, 11, 0),
            new Optcode("BPL x", 0x10, 11, 0),
            new Optcode("BVC x", 0x50, 11, 0),
            new Optcode("BVS x", 0x70, 11, 0),
            new Optcode("BRA x", 0x80, 11, 0),
            new Optcode("BRL ?", 0x82, 9, 0),
            new Optcode("BCC.B x", 0x90, 11, 0),
            new Optcode("BCS.B x", 0xB0, 11, 0),
            new Optcode("BEQ.B x", 0xF0, 11, 0),
            new Optcode("BNE.B x", 0xD0, 11, 0),
            new Optcode("BMI.B x", 0x30, 11, 0),
            new Optcode("BPL.B x", 0x10, 11, 0),
            new Optcode("BVC.B x", 0x50, 11, 0),
            new Optcode("BVS.B x", 0x70, 11, 0),
            new Optcode("BRA.B x", 0x80, 11, 0),
            new Optcode("BRL.W ?", 0x82, 9, 0),

            new Optcode("BIT #x", 0x89, 4, 0),
            new Optcode("BIT x", 0x24, 0xA, 2),
            new Optcode("BIT ?", 0x2C, 2, 0),
            new Optcode("BIT x,X", 0x34, 0xA, 2),
            new Optcode("BIT ?,X", 0x3C, 2, 0),
            new Optcode("BIT.B #x", 0x89, 0xA, 0),
            new Optcode("BIT.W #?", 0x89, 2, 0),
            new Optcode("BIT.B x", 0x24, 0xA, 0),
            new Optcode("BIT.W ?", 0x2C, 2, 0),
            new Optcode("BIT.B x,X", 0x34, 0xA, 0),
            new Optcode("BIT.W ?,X", 0x3C, 2, 0),

            new Optcode("BRK x", 0x00, 0xA, 0),
            new Optcode("BRK.B x", 0x00, 0xA, 0),
            new Optcode("BRK", 0x0000, 8, 0),

            new Optcode("CLC", 0x18, 0, 0),
            new Optcode("CLD", 0xD8, 0, 0),
            new Optcode("CLI", 0x58, 0, 0),
            new Optcode("CLV", 0xB8, 0, 0),

            new Optcode("CMP #x", 0xC9, 4, 0),
            new Optcode("CMP (x)", 0xD2, 0xA, 0),
            new Optcode("CMP [x]", 0xC7, 0xA, 0),
            new Optcode("CMP (x,X)", 0xC1, 0xA, 0),
            new Optcode("CMP (x),Y", 0xD1, 0xA, 0),
            new Optcode("CMP (x,S),Y", 0xD3, 0xA, 0),
            new Optcode("CMP [x],Y", 0xD7, 0xA, 0),
            new Optcode("CMP x", 0xC5, 0xA, 2),
            new Optcode("CMP ?", 0xCD, 2, 1),
            new Optcode("CMP &", 0xCF, 3, 0),
            new Optcode("CMP x,X", 0xD5, 0xA, 2),
            new Optcode("CMP ?,X", 0xDD, 2, 1),
            new Optcode("CMP &,X", 0xDF, 3, 0),
            new Optcode("CMP ?,Y", 0xD9, 2, 0),
            new Optcode("CMP x,S", 0xC3, 0xA, 0),
            new Optcode("CMP.B #x", 0xC9, 0xA, 0),
            new Optcode("CMP.W #?", 0xC9, 2, 0),
            new Optcode("CMP.B (x)", 0xD2, 0xA, 0),
            new Optcode("CMP.B [x]", 0xC7, 0xA, 0),
            new Optcode("CMP.B (x,X)", 0xC1, 0xA, 0),
            new Optcode("CMP.B (x),Y", 0xD1, 0xA, 0),
            new Optcode("CMP.B (x,S),Y", 0xD3, 0xA, 0),
            new Optcode("CMP.B [x],Y", 0xD7, 0xA, 0),
            new Optcode("CMP.B x", 0xC5, 0xA, 0),
            new Optcode("CMP.W ?", 0xCD, 2, 0),
            new Optcode("CMP.L &", 0xCF, 3, 0),
            new Optcode("CMP.B x,X", 0xD5, 0xA, 0),
            new Optcode("CMP.W ?,X", 0xDD, 2, 0),
            new Optcode("CMP.L &,X", 0xDF, 3, 0),
            new Optcode("CMP.W ?,Y", 0xD9, 2, 0),
            new Optcode("CMP.B x,S", 0xC3, 0xA, 0),

            new Optcode("COP x", 0x02, 0xA, 0),
            new Optcode("COP.B x", 0x02, 0xA, 0),
            new Optcode("COP", 0x0200, 8, 0),

            new Optcode("CPX #x", 0xE0, 7, 0),
            new Optcode("CPX x", 0xE4, 0xA, 2),
            new Optcode("CPX ?", 0xEC, 2, 0),
            new Optcode("CPX.B #x", 0xE0, 0xA, 0),
            new Optcode("CPX.W #?", 0xE0, 2, 0),
            new Optcode("CPX.B x", 0xE4, 0xA, 0),
            new Optcode("CPX.W ?", 0xEC, 2, 0),

            new Optcode("CPY #x", 0xC0, 7, 0),
            new Optcode("CPY x", 0xC4, 0xA, 2),
            new Optcode("CPY ?", 0xCC, 2, 0),
            new Optcode("CPY.B #x", 0xC0, 0xA, 0),
            new Optcode("CPY.W #?", 0xC0, 2, 0),
            new Optcode("CPY.B x", 0xC4, 0xA, 0),
            new Optcode("CPY.W ?", 0xCC, 2, 0),

            new Optcode("DEA", 0x3A, 0, 0),
            new Optcode("DEX", 0xCA, 0, 0),
            new Optcode("DEY", 0x88, 0, 0),
            new Optcode("DEC A", 0x3A, 0, 0),
            new Optcode("DEC x", 0xC6, 0xA, 2),
            new Optcode("DEC ?", 0xCE, 2, 0),
            new Optcode("DEC x,X", 0xD6, 0xA, 2),
            new Optcode("DEC ?,X", 0xDE, 2, 0),
            new Optcode("DEC.B x", 0xC6, 0xA, 0),
            new Optcode("DEC.W ?", 0xCE, 2, 0),
            new Optcode("DEC.B x,X", 0xD6, 0xA, 0),
            new Optcode("DEC.W ?,X", 0xDE, 2, 0),

            new Optcode("EOR #x", 0x49, 4, 0),
            new Optcode("EOR (x)", 0x52, 0xA, 0),
            new Optcode("EOR [x]", 0x47, 0xA, 0),
            new Optcode("EOR (x,X)", 0x41, 0xA, 0),
            new Optcode("EOR (x),Y", 0x51, 0xA, 0),
            new Optcode("EOR (x,S),Y", 0x53, 0xA, 0),
            new Optcode("EOR [x],Y", 0x57, 0xA, 0),
            new Optcode("EOR x", 0x45, 0xA, 2),
            new Optcode("EOR ?", 0x4D, 2, 1),
            new Optcode("EOR &", 0x4F, 3, 0),
            new Optcode("EOR x,X", 0x55, 0xA, 2),
            new Optcode("EOR ?,X", 0x5D, 2, 1),
            new Optcode("EOR &,X", 0x5F, 3, 0),
            new Optcode("EOR ?,Y", 0x59, 2, 0),
            new Optcode("EOR x,S", 0x43, 0xA, 0),
            new Optcode("EOR.B #x", 0x49, 0xA, 0),
            new Optcode("EOR.W #?", 0x49, 2, 0),
            new Optcode("EOR.B (x)", 0x52, 0xA, 0),
            new Optcode("EOR.B [x]", 0x47, 0xA, 0),
            new Optcode("EOR.B (x,X)", 0x41, 0xA, 0),
            new Optcode("EOR.B (x),Y", 0x51, 0xA, 0),
            new Optcode("EOR.B (x,S),Y", 0x53, 0xA, 0),
            new Optcode("EOR.B [x],Y", 0x57, 0xA, 0),
            new Optcode("EOR.B x", 0x45, 0xA, 0),
            new Optcode("EOR.W ?", 0x4D, 2, 0),
            new Optcode("EOR.L &", 0x4F, 3, 0),
            new Optcode("EOR.B x,X", 0x55, 0xA, 0),
            new Optcode("EOR.W ?,X", 0x5D, 2, 0),
            new Optcode("EOR.L &,X", 0x5F, 3, 0),
            new Optcode("EOR.W ?,Y", 0x59, 2, 0),
            new Optcode("EOR.B x,S", 0x43, 0xA, 0),

            new Optcode("INA", 0x1A, 0, 0),
            new Optcode("INX", 0xE8, 0, 0),
            new Optcode("INY", 0xC8, 0, 0),
            new Optcode("INC A", 0x1A, 0, 0),
            new Optcode("INC x", 0xE6, 0xA, 2),
            new Optcode("INC ?", 0xEE, 2, 0),
            new Optcode("INC x,X", 0xF6, 0xA, 2),
            new Optcode("INC ?,X", 0xFE, 2, 0),
            new Optcode("INC.B x", 0xE6, 0xA, 0),
            new Optcode("INC.W ?", 0xEE, 2, 0),
            new Optcode("INC.B x,X", 0xF6, 0xA, 0),
            new Optcode("INC.W ?,X", 0xFE, 2, 0),

            new Optcode("JMP (?)", 0x6C, 2, 0),
            new Optcode("JMP (?,X)", 0x7C, 2, 0),
            new Optcode("JMP [?]", 0xDC, 2, 0),
            new Optcode("JML [?]", 0xDC, 2, 0),
            new Optcode("JMP ?", 0x4C, 2, 1),
            new Optcode("JMP &", 0x5C, 3, 0),
            new Optcode("JML &", 0x5C, 3, 0),
            new Optcode("JMP.W (?)", 0x6C, 2, 0),
            new Optcode("JMP.W (?,X)", 0x7C, 2, 0),
            new Optcode("JMP.W [?]", 0xDC, 2, 0),
            new Optcode("JML.W [?]", 0xDC, 2, 0),
            new Optcode("JMP.W ?", 0x4C, 2, 0),
            new Optcode("JMP.L &", 0x5C, 3, 0),
            new Optcode("JML.L &", 0x5C, 3, 0),

            new Optcode("JSR (?,X)", 0xFC, 2, 0),
            new Optcode("JSR ?", 0x20, 2, 1),
            new Optcode("JSR &", 0x22, 3, 0),
            new Optcode("JSL &", 0x22, 3, 0),
            new Optcode("JSR.W (?,X)", 0xFC, 2, 0),
            new Optcode("JSR.W ?", 0x20, 2, 0),
            new Optcode("JSR.L &", 0x22, 3, 0),
            new Optcode("JSL.L &", 0x22, 3, 0),

            new Optcode("LDA #x", 0xA9, 4, 0),
            new Optcode("LDA (x)", 0xB2, 0xA, 0),
            new Optcode("LDA [x]", 0xA7, 0xA, 0),
            new Optcode("LDA (x,X)", 0xA1, 0xA, 0),
            new Optcode("LDA (x),Y", 0xB1, 0xA, 0),
            new Optcode("LDA (x,S),Y", 0xB3, 0xA, 0),
            new Optcode("LDA [x],Y", 0xB7, 0xA, 0),
            new Optcode("LDA x", 0xA5, 0xA, 2),
            new Optcode("LDA ?", 0xAD, 2, 1),
            new Optcode("LDA &", 0xAF, 3, 0),
            new Optcode("LDA x,X", 0xB5, 0xA, 2),
            new Optcode("LDA ?,X", 0xBD, 2, 1),
            new Optcode("LDA &,X", 0xBF, 3, 0),
            new Optcode("LDA ?,Y", 0xB9, 2, 0),
            new Optcode("LDA x,S", 0xA3, 0xA, 0),
            new Optcode("LDA.B #x", 0xA9, 0xA, 0),
            new Optcode("LDA.W #?", 0xA9, 2, 0),
            new Optcode("LDA.B (x)", 0xB2, 0xA, 0),
            new Optcode("LDA.B [x]", 0xA7, 0xA, 0),
            new Optcode("LDA.B (x,X)", 0xA1, 0xA, 0),
            new Optcode("LDA.B (x),Y", 0xB1, 0xA, 0),
            new Optcode("LDA.B (x,S),Y", 0xB3, 0xA, 0),
            new Optcode("LDA.B [x],Y", 0xB7, 0xA, 0),
            new Optcode("LDA.B x", 0xA5, 0xA, 0),
            new Optcode("LDA.W ?", 0xAD, 2, 0),
            new Optcode("LDA.L &", 0xAF, 3, 0),
            new Optcode("LDA.B x,X", 0xB5, 0xA, 0),
            new Optcode("LDA.W ?,X", 0xBD, 2, 0),
            new Optcode("LDA.L &,X", 0xBF, 3, 0),
            new Optcode("LDA.W ?,Y", 0xB9, 2, 0),
            new Optcode("LDA.B x,S", 0xA3, 0xA, 0),

            new Optcode("LDX #x", 0xA2, 7, 0),
            new Optcode("LDX x", 0xA6, 0xA, 2),
            new Optcode("LDX ?", 0xAE, 2, 0),
            new Optcode("LDX x,Y", 0xB6, 0xA, 2),
            new Optcode("LDX ?,Y", 0xBE, 2, 0),
            new Optcode("LDX.B #x", 0xA2, 0xA, 0),
            new Optcode("LDX.W #?", 0xA2, 2, 0),
            new Optcode("LDX.B x", 0xA6, 0xA, 0),
            new Optcode("LDX.W ?", 0xAE, 2, 0),
            new Optcode("LDX.B x,Y", 0xB6, 0xA, 0),
            new Optcode("LDX.W ?,Y", 0xBE, 2, 0),

            new Optcode("LDY #x", 0xA0, 7, 0),
            new Optcode("LDY x", 0xA4, 0xA, 2),
            new Optcode("LDY ?", 0xAC, 2, 0),
            new Optcode("LDY x,X", 0xB4, 0xA, 2),
            new Optcode("LDY ?,X", 0xBC, 2, 0),
            new Optcode("LDY.B #x", 0xA0, 0xA, 0),
            new Optcode("LDY.W #?", 0xA0, 2, 0),
            new Optcode("LDY.B x", 0xA4, 0xA, 0),
            new Optcode("LDY.W ?", 0xAC, 2, 0),
            new Optcode("LDY.B x,X", 0xB4, 0xA, 0),
            new Optcode("LDY.W ?,X", 0xBC, 2, 0),

            new Optcode("LSR A", 0x4A, 0, 0),
            new Optcode("LSR", 0x4A, 0, 0),
            new Optcode("LSR x", 0x46, 0xA, 2),
            new Optcode("LSR ?", 0x4E, 2, 0),
            new Optcode("LSR x,X", 0x56, 0xA, 2),
            new Optcode("LSR ?,X", 0x5E, 2, 0),
            new Optcode("LSR.B x", 0x46, 0xA, 0),
            new Optcode("LSR.W ?", 0x4E, 2, 0),
            new Optcode("LSR.B x,X", 0x56, 0xA, 0),
            new Optcode("LSR.W ?,X", 0x5E, 2, 0),

            new Optcode("MVN x,x", 0x54, 5, 0),
            new Optcode("MVP x,x", 0x44, 5, 0),
            new Optcode("MVN.B x,x", 0x54, 5, 0),
            new Optcode("MVP.B x,x", 0x44, 5, 0),

            new Optcode("NOP", 0xEA, 0, 0),

            new Optcode("ORA #x", 0x09, 4, 0),
            new Optcode("ORA (x)", 0x12, 0xA, 0),
            new Optcode("ORA [x]", 0x07, 0xA, 0),
            new Optcode("ORA (x,X)", 0x01, 0xA, 0),
            new Optcode("ORA (x),Y", 0x11, 0xA, 0),
            new Optcode("ORA (x,S),Y", 0x13, 0xA, 0),
            new Optcode("ORA [x],Y", 0x17, 0xA, 0),
            new Optcode("ORA x", 0x05, 0xA, 2),
            new Optcode("ORA ?", 0x0D, 2, 1),
            new Optcode("ORA &", 0x0F, 3, 0),
            new Optcode("ORA x,X", 0x15, 0xA, 2),
            new Optcode("ORA ?,X", 0x1D, 2, 1),
            new Optcode("ORA &,X", 0x1F, 3, 0),
            new Optcode("ORA ?,Y", 0x19, 2, 0),
            new Optcode("ORA x,S", 0x03, 0xA, 0),
            new Optcode("ORA.B #x", 0x09, 0xA, 0),
            new Optcode("ORA.W #?", 0x09, 2, 0),
            new Optcode("ORA.B (x)", 0x12, 0xA, 0),
            new Optcode("ORA.B [x]", 0x07, 0xA, 0),
            new Optcode("ORA.B (x,X)", 0x01, 0xA, 0),
            new Optcode("ORA.B (x),Y", 0x11, 0xA, 0),
            new Optcode("ORA.B (x,S),Y", 0x13, 0xA, 0),
            new Optcode("ORA.B [x],Y", 0x17, 0xA, 0),
            new Optcode("ORA.B x", 0x05, 0xA, 0),
            new Optcode("ORA.W ?", 0x0D, 2, 0),
            new Optcode("ORA.L &", 0x0F, 3, 0),
            new Optcode("ORA.B x,X", 0x15, 0xA, 0),
            new Optcode("ORA.W ?,X", 0x1D, 2, 0),
            new Optcode("ORA.L &,X", 0x1F, 3, 0),
            new Optcode("ORA.W ?,Y", 0x19, 2, 0),
            new Optcode("ORA.B x,S", 0x03, 0xA, 0),

            new Optcode("PEA ?", 0xF4, 2, 0),
            new Optcode("PEA.W ?", 0xF4, 2, 0),
            new Optcode("PEI (x)", 0xD4, 0xA, 0),
            new Optcode("PEI.B (x)", 0xD4, 0xA, 0),
            new Optcode("PER ?", 0x62, 9, 0),
            new Optcode("PER.W ?", 0x62, 9, 0),

            new Optcode("PHA", 0x48, 0, 0),
            new Optcode("PHP", 0x08, 0, 0),
            new Optcode("PHX", 0xDA, 0, 0),
            new Optcode("PHY", 0x5A, 0, 0),
            new Optcode("PLA", 0x68, 0, 0),
            new Optcode("PLP", 0x28, 0, 0),
            new Optcode("PLX", 0xFA, 0, 0),
            new Optcode("PLY", 0x7A, 0, 0),

            new Optcode("PHB", 0x8B, 0, 0),
            new Optcode("PHD", 0x0B, 0, 0),
            new Optcode("PHK", 0x4B, 0, 0),
            new Optcode("PLB", 0xAB, 0, 0),
            new Optcode("PLD", 0x2B, 0, 0),

            new Optcode("REP #x", 0xC2, 6, 0),
            new Optcode("REP.B #x", 0xC2, 6, 0),

            new Optcode("ROL A", 0x2A, 0, 0),
            new Optcode("ROL", 0x2A, 0, 0),
            new Optcode("ROL x", 0x26, 0xA, 2),
            new Optcode("ROL ?", 0x2E, 2, 0),
            new Optcode("ROL x,X", 0x36, 0xA, 2),
            new Optcode("ROL ?,X", 0x3E, 2, 0),
            new Optcode("ROL.B x", 0x26, 0xA, 0),
            new Optcode("ROL.W ?", 0x2E, 2, 0),
            new Optcode("ROL.B x,X", 0x36, 0xA, 0),
            new Optcode("ROL.W ?,X", 0x3E, 2, 0),

            new Optcode("ROR A", 0x6A, 0, 0),
            new Optcode("ROR", 0x6A, 0, 0),
            new Optcode("ROR x", 0x66, 0xA, 2),
            new Optcode("ROR ?", 0x6E, 2, 0),
            new Optcode("ROR x,X", 0x76, 0xA, 2),
            new Optcode("ROR ?,X", 0x7E, 2, 0),
            new Optcode("ROR.B x", 0x66, 0xA, 0),
            new Optcode("ROR.W ?", 0x6E, 2, 0),
            new Optcode("ROR.B x,X", 0x76, 0xA, 0),
            new Optcode("ROR.W ?,X", 0x7E, 2, 0),

            new Optcode("RTI", 0x40, 0, 0),
            new Optcode("RTL", 0x6B, 0, 0),
            new Optcode("RTS", 0x60, 0, 0),

            new Optcode("SEC", 0x38, 0, 0),
            new Optcode("SED", 0xF8, 0, 0),
            new Optcode("SEI", 0x78, 0, 0),

            new Optcode("SBC #x", 0xE9, 4, 0),
            new Optcode("SBC (x)", 0xF2, 0xA, 0),
            new Optcode("SBC [x]", 0xE7, 0xA, 0),
            new Optcode("SBC (x,X)", 0xE1, 0xA, 0),
            new Optcode("SBC (x),Y", 0xF1, 0xA, 0),
            new Optcode("SBC (x,S),Y", 0xF3, 0xA, 0),
            new Optcode("SBC [x],Y", 0xF7, 0xA, 0),
            new Optcode("SBC x", 0xE5, 0xA, 2),
            new Optcode("SBC ?", 0xED, 2, 1),
            new Optcode("SBC &", 0xEF, 3, 0),
            new Optcode("SBC x,X", 0xF5, 0xA, 2),
            new Optcode("SBC ?,X", 0xFD, 2, 1),
            new Optcode("SBC &,X", 0xFF, 3, 0),
            new Optcode("SBC ?,Y", 0xF9, 2, 0),
            new Optcode("SBC x,S", 0xE3, 0xA, 0),
            new Optcode("SBC.B #x", 0xE9, 0xA, 0),
            new Optcode("SBC.W #?", 0xE9, 2, 0),
            new Optcode("SBC.B (x)", 0xF2, 0xA, 0),
            new Optcode("SBC.B [x]", 0xE7, 0xA, 0),
            new Optcode("SBC.B (x,X)", 0xE1, 0xA, 0),
            new Optcode("SBC.B (x),Y", 0xF1, 0xA, 0),
            new Optcode("SBC.B (x,S),Y", 0xF3, 0xA, 0),
            new Optcode("SBC.B [x],Y", 0xF7, 0xA, 0),
            new Optcode("SBC.B x", 0xE5, 0xA, 0),
            new Optcode("SBC.W ?", 0xED, 2, 0),
            new Optcode("SBC.L &", 0xEF, 3, 0),
            new Optcode("SBC.B x,X", 0xF5, 0xA, 0),
            new Optcode("SBC.W ?,X", 0xFD, 2, 0),
            new Optcode("SBC.L &,X", 0xFF, 3, 0),
            new Optcode("SBC.W ?,Y", 0xF9, 2, 0),
            new Optcode("SBC.B x,S", 0xE3, 0xA, 0),

            new Optcode("SEP #x", 0xE2, 6, 1),
            new Optcode("SEP.B #x", 0xE2, 6, 1),

            new Optcode("STA (x)", 0x92, 0xA, 0),
            new Optcode("STA [x]", 0x87, 0xA, 0),
            new Optcode("STA (x,X)", 0x81, 0xA, 0),
            new Optcode("STA (x),Y", 0x91, 0xA, 0),
            new Optcode("STA (x,S),Y", 0x93, 0xA, 0),
            new Optcode("STA [x],Y", 0x97, 0xA, 0),
            new Optcode("STA x", 0x85, 0xA, 2),
            new Optcode("STA ?", 0x8D, 2, 1),
            new Optcode("STA &", 0x8F, 3, 0),
            new Optcode("STA x,X", 0x95, 0xA, 2),
            new Optcode("STA ?,X", 0x9D, 2, 1),
            new Optcode("STA &,X", 0x9F, 3, 0),
            new Optcode("STA ?,Y", 0x99, 2, 0),
            new Optcode("STA x,S", 0x83, 0xA, 0),
            new Optcode("STA.B (x)", 0x92, 0xA, 0),
            new Optcode("STA.B [x]", 0x87, 0xA, 0),
            new Optcode("STA.B (x,X)", 0x81, 0xA, 0),
            new Optcode("STA.B (x),Y", 0x91, 0xA, 0),
            new Optcode("STA.B (x,S),Y", 0x93, 0xA, 0),
            new Optcode("STA.B [x],Y", 0x97, 0xA, 0),
            new Optcode("STA.B x", 0x85, 0xA, 0),
            new Optcode("STA.W ?", 0x8D, 2, 0),
            new Optcode("STA.L &", 0x8F, 3, 0),
            new Optcode("STA.B x,X", 0x95, 0xA, 0),
            new Optcode("STA.W ?,X", 0x9D, 2, 0),
            new Optcode("STA.L &,X", 0x9F, 3, 0),
            new Optcode("STA.W ?,Y", 0x99, 2, 0),
            new Optcode("STA.B x,S", 0x83, 0xA, 0),

            new Optcode("STP", 0xDB, 0, 0),

            new Optcode("STX x", 0x86, 0xA, 2),
            new Optcode("STX ?", 0x8E, 2, 0),
            new Optcode("STX x,Y", 0x96, 0xA, 0),
            new Optcode("STX.B x", 0x86, 0xA, 0),
            new Optcode("STX.W ?", 0x8E, 2, 0),
            new Optcode("STX.B x,Y", 0x96, 0xA, 0),

            new Optcode("STY x", 0x84, 0xA, 2),
            new Optcode("STY ?", 0x8C, 2, 0),
            new Optcode("STY x,X", 0x94, 0xA, 0),
            new Optcode("STY.B x", 0x84, 0xA, 0),
            new Optcode("STY.W ?", 0x8C, 2, 0),
            new Optcode("STY.B x,X", 0x94, 0xA, 0),

            new Optcode("STZ x", 0x64, 0xA, 2),
            new Optcode("STZ ?", 0x9C, 2, 0),
            new Optcode("STZ x,X", 0x74, 0xA, 2),
            new Optcode("STZ ?,X", 0x9E, 2, 0),
            new Optcode("STZ.B x", 0x64, 0xA, 0),
            new Optcode("STZ.W ?", 0x9C, 2, 0),
            new Optcode("STZ.B x,X", 0x74, 0xA, 0),
            new Optcode("STZ.W ?,X", 0x9E, 2, 0),

            new Optcode("SWA", 0xEB, 0, 0),

            new Optcode("TAX", 0xAA, 0, 0),
            new Optcode("TAY", 0xA8, 0, 0),
            new Optcode("TXA", 0x8A, 0, 0),
            new Optcode("TYA", 0x98, 0, 0),
            new Optcode("TSX", 0xBA, 0, 0),
            new Optcode("TXS", 0x9A, 0, 0),
            new Optcode("TXY", 0x9B, 0, 0),
            new Optcode("TYX", 0xBB, 0, 0),

            new Optcode("TCD", 0x5B, 0, 0),
            new Optcode("TAD", 0x5B, 0, 0),
            new Optcode("TDC", 0x7B, 0, 0),
            new Optcode("TDA", 0x7B, 0, 0),

            new Optcode("TCS", 0x1B, 0, 0),
            new Optcode("TAS", 0x1B, 0, 0),
            new Optcode("TSC", 0x3B, 0, 0),
            new Optcode("TSA", 0x3B, 0, 0),

            new Optcode("TRB x", 0x14, 0xA, 2),
            new Optcode("TRB ?", 0x1C, 2, 0),
            new Optcode("TSB x", 0x04, 0xA, 2),
            new Optcode("TSB ?", 0x0C, 2, 0),
            new Optcode("TRB.B x", 0x14, 0xA, 0),
            new Optcode("TRB.W ?", 0x1C, 2, 0),
            new Optcode("TSB.B x", 0x04, 0xA, 0),
            new Optcode("TSB.W ?", 0x0C, 2, 0),

            new Optcode("WAI", 0xCB, 0, 0),
            new Optcode("WDM", 0x42, 0, 0),

            new Optcode("XBA", 0xEB, 0, 0),
            new Optcode("XCE", 0xFB, 0, 0),

            new Optcode("E", 0x100, -1, 0)
    };

}
